EventVars['Cities'] = [{description: "Tokyo", objects: "13 subway lines;visit the emperor at the Imperial Palace;the busiest street crossing in the world outside Shibuya Station;Skytree, the world's tallest tower;375 Michelin stars, most in the world;world's biggest fish market;more noodle shops than anywhere else;", location: "Japan", date: "35.7", actor: "37.1 million", category: "Pacific Islands", image: "Tokyo.png", topic: "Cities", URL: ""},
{description: "Jakarta", objects: "", location: "Indonesia", date: "-6.2", actor: "26.0 million", category: "South Asia", image: "Jakarta.png", topic: "Cities", URL: ""},
{description: "Seoul", objects: "", location: "South Korea", date: "37.6", actor: "22.5 million", category: "South Asia", image: "Seoul.png", topic: "Cities", URL: ""},
{description: "Delhi", objects: "", location: "India", date: "28.6", actor: "22.2 million", category: "South Asia", image: "Delhi.png", topic: "Cities", URL: ""},
{description: "Shanghai", objects: "", location: "China", date: "31.2", actor: "20.9 million", category: "Asia", image: "Shanghai.png", topic: "Cities", URL: ""},
{description: "Manila", objects: "", location: "Philippines", date: "14.6", actor: "20.8 million", category: "Pacific Islands", image: "Manila.png", topic: "Cities", URL: ""},
{description: "Karachi", objects: "", location: "Pakistan", date: "24.9", actor: "20.7 million", category: "South Asia", image: "Karachi.png", topic: "Cities", URL: ""},
{description: "New York", objects: "The Big Apple", location: "United States", date: "40.7", actor: "20.5 million", category: "North America", image: "NewYork.png", topic: "Cities", URL: ""},
{description: "Sao Paulo", objects: "", location: "Brazil", date: "-23.6", actor: "20.2 million", category: "South America", image: "SaoPaulo.png", topic: "Cities", URL: ""},
{description: "Mexico City", objects: "", location: "Mexico", date: "19.4", actor: "19.5 million", category: "Central America", image: "MexicoCity.png", topic: "Cities", URL: ""},
{description: "Cairo", objects: "", location: "Egypt", date: "30.1", actor: "17.8 million", category: "Africa", image: "Cairo.png", topic: "Cities", URL: ""},
{description: "Beijing", objects: "", location: "China", date: "39.9", actor: "17.3 million", category: "Asia", image: "Beijing.png", topic: "Cities", URL: ""},
{description: "Osaka", objects: "", location: "Japan", date: "34.7", actor: "17.0 million", category: "Pacific Islands", image: "Osaka.png", topic: "Cities", URL: ""},
{description: "Mumbai", objects: "", location: "India", date: "19", actor: "16.9 million", category: "South Asia", image: "Mumbai.png", topic: "Cities", URL: ""},
{description: "Guangzhou", objects: "", location: "China", date: "23.1", actor: "16.8 million", category: "Asia", image: "Guangzhou.png", topic: "Cities", URL: ""},
{description: "Moscow", objects: "", location: "Russia", date: "55.8", actor: "15.5 million", category: "Europe", image: "Moscow.png", topic: "Cities", URL: ""},
{description: "Los Angeles", objects: "City of Angels", location: "United States", date: "34.1", actor: "14.9 million", category: "North America", image: "LosAngeles.png", topic: "Cities", URL: ""},
{description: "Calcutta", objects: "City of Palaces", location: "India", date: "22.6", actor: "14.4 million", category: "South Asia", image: "Calcutta.png", topic: "Cities", URL: ""},
{description: "Dhaka", objects: "", location: "Bangladesh", date: "23.7", actor: "14.0 million", category: "South Asia", image: "Dhaka.png", topic: "Cities", URL: ""},
{description: "Buenos Aires", objects: "", location: "Argentina", date: "-34.6", actor: "13.6 million", category: "South America", image: "BuenosAires.png", topic: "Cities", URL: ""},
{description: "Istanbul", objects: "", location: "Turkey", date: "41", actor: "13.6 million", category: "Europe", image: "Istanbul.png", topic: "Cities", URL: ""},
{description: "Rio de Janeiro", objects: "", location: "Brazil", date: "-22.9", actor: "12.0 million", category: "South America", image: "RiodeJaneiro.png", topic: "Cities", URL: ""},
{description: "Shenzhen", objects: "", location: "China", date: "22.5", actor: "11.9 million", category: "Asia", image: "Shenzhen.png", topic: "Cities", URL: ""},
{description: "Lagos", objects: "", location: "Nigeria", date: "6.5", actor: "11.5 million", category: "Africa", image: "Lagos.png", topic: "Cities", URL: ""},
{description: "Paris", objects: "", location: "France", date: "48.9", actor: "10.8 million", category: "Europe", image: "Paris.png", topic: "Cities", URL: ""},
{description: "Nagoya", objects: "", location: "Japan", date: "35.2", actor: "10.0 million", category: "Pacific Islands", image: "Nagoya.png", topic: "Cities", URL: ""},
{description: "Lima", objects: "", location: "Peru", date: "-12", actor: "9.1 million", category: "South America", image: "Lima.png", topic: "Cities", URL: ""},
{description: "Chicago", objects: "", location: "United States", date: "41.9", actor: "9.1 million", category: "North America", image: "Chicago.png", topic: "Cities", URL: ""},
{description: "Kinshasa", objects: "", location: "Congo", date: "-4.3", actor: "9.0 million", category: "Africa", image: "Kinshasa.png", topic: "Cities", URL: ""},
{description: "Tianjin", objects: "", location: "China", date: "39.1", actor: "8.9 million", category: "Asia", image: "Tianjin.png", topic: "Cities", URL: ""},
{description: "Chennai", objects: "", location: "India", date: "13.1", actor: "8.9 million", category: "South Asia", image: "Chennai.png", topic: "Cities", URL: ""},
{description: "Bogota", objects: "", location: "Colombia", date: "4.6", actor: "8.7 million", category: "South America", image: "Bogota.png", topic: "Cities", URL: ""},
{description: "Bengaluru", objects: "", location: "India", date: "13", actor: "8.7 million", category: "South Asia", image: "Bengaluru.png", topic: "Cities", URL: ""},
{description: "London", objects: "", location: "Great Britain", date: "51.5", actor: "8.6 million", category: "Europe", image: "London.png", topic: "Cities", URL: ""},
{description: "Taipei", objects: "", location: "Taiwan", date: "23", actor: "8.3 million", category: "Pacific Islands", image: "Taipei.png", topic: "Cities", URL: ""},
{description: "Ho Chi Minh City", objects: "", location: "Vietnam", date: "10.8", actor: "8.3 million", category: "South Asia", image: "HoChiMinhCity.png", topic: "Cities", URL: ""},
{description: "Dongguan", objects: "", location: "China", date: "23", actor: "8.3 million", category: "Asia", image: "Dongguan.png", topic: "Cities", URL: ""},
{description: "Hyderabad", objects: "", location: "India", date: "17.4", actor: "7.9 million", category: "South Asia", image: "Hyderabad.png", topic: "Cities", URL: ""},
{description: "Chengdu", objects: "motto: once you visit you never want to leave", location: "China", date: "30.7", actor: "7.9 million", category: "Asia", image: "Chengdu.png", topic: "Cities", URL: ""},
{description: "Lahore", objects: "", location: "Pakistan", date: "31.5", actor: "7.7 million", category: "South Asia", image: "Lahore.png", topic: "Cities", URL: ""},
{description: "Johannesburg", objects: "", location: "South Africa", date: "-26.2", actor: "7.6 million", category: "Africa", image: "Johannesburg.png", topic: "Cities", URL: ""},
{description: "Tehran", objects: "", location: "Iran", date: "35.7", actor: "7.4 million", category: "Middle East", image: "Tehran.png", topic: "Cities", URL: ""},
{description: "Essen", objects: "", location: "Germany", date: "51.5", actor: "7.3 million", category: "Europe", image: "Essen.png", topic: "Cities", URL: ""},
{description: "Bangkok", objects: "", location: "Thailand", date: "13.8", actor: "7.1 million", category: "South Asia", image: "Bangkok.png", topic: "Cities", URL: ""},
{description: "Hong Kong", objects: "", location: "Hong Kong", date: "22.3", actor: "7.1 million", category: "Pacific Islands", image: "HongKong.png", topic: "Cities", URL: ""},
{description: "Wuhan", objects: "", location: "China", date: "30.6", actor: "7.0 million", category: "Asia", image: "Wuhan.png", topic: "Cities", URL: ""},
{description: "Ahmedabad", objects: "", location: "India", date: "23", actor: "6.5 million", category: "South Asia", image: "Ahmedabad.png", topic: "Cities", URL: ""},
{description: "Chongqing", objects: "", location: "China", date: "29.6", actor: "6.3 million", category: "Asia", image: "Chongqing.png", topic: "Cities", URL: ""},
{description: "Baghdad", objects: "", location: "Iraq", date: "32.3", actor: "6.2 million", category: "Middle East", image: "Baghdad.png", topic: "Cities", URL: ""},
{description: "Hangzhou", objects: "", location: "China", date: "30.3", actor: "6.2 million", category: "Asia", image: "Hangzhou.png", topic: "Cities", URL: ""},
{description: "Toronto", objects: "motto: the world within a city", location: "Canada", date: "43.7", actor: "6.1 million", category: "North America", image: "Toronto.png", topic: "Cities", URL: ""},
{description: "Kuala Lumpur", objects: "", location: "Malaysia", date: "3.1", actor: "6.1 million", category: "South Asia", image: "KualaLumpur.png", topic: "Cities", URL: ""},
{description: "Santiago", objects: "", location: "Chile", date: "-33.5", actor: "6.0 million", category: "South America", image: "Santiago.png", topic: "Cities", URL: ""},
{description: "San Francisco", objects: "", location: "United States", date: "37.8", actor: "5.9 million", category: "North America", image: "SanFrancisco.png", topic: "Cities", URL: ""},
{description: "Miami", objects: "", location: "United States", date: "25.8", actor: "5.6 million", category: "North America", image: "Miami.png", topic: "Cities", URL: ""},
{description: "Philadelphia", objects: "", location: "United States", date: "40", actor: "5.5 million", category: "North America", image: "Philadelphia.png", topic: "Cities", URL: ""},
{description: "Nanjing", objects: "", location: "China", date: "32.1", actor: "5.5 million", category: "Asia", image: "Nanjing.png", topic: "Cities", URL: ""},
{description: "Madrid", objects: "", location: "Spain", date: "40.4", actor: "5.4 million", category: "Europe", image: "Madrid.png", topic: "Cities", URL: ""},
{description: "Houston", objects: "", location: "United States", date: "29.8", actor: "5.4 million", category: "North America", image: "Houston.png", topic: "Cities", URL: ""},
{description: "Milan", objects: "", location: "Italy", date: "45.5", actor: "5.2 million", category: "Europe", image: "Milan.png", topic: "Cities", URL: ""},
{description: "Singapore", objects: "", location: "Singapore", date: "1.3", actor: "5.2 million", category: "South Asia", image: "Singapore.png", topic: "Cities", URL: "."},
{description: "Saint Petersburg", objects: "", location: "Russia", date: "60", actor: "4.9 million", category: "Europe", image: "StPetersburg.png", topic: "Cities", URL: ""},
{description: "Altanta", objects: "", location: "United States", date: "33.8", actor: "4.7 million", category: "North America", image: "Atlanta.png", topic: "Cities", URL: ""},
{description: "Washington, D.C.", objects: "", location: "United States", date: "38.9", actor: "4.7 million", category: "North America", image: "WashingtonDC.png", topic: "Cities", URL: ""},
{description: "Yangoon", objects: "", location: "Myanmar", date: "16.8", actor: "4.5 million", category: "South Asia", image: "Yangoon.png", topic: "Cities", URL: ""},
{description: "Alexandria", objects: "", location: "Egypt", date: "31.2", actor: "4.5 million", category: "Africa", image: "Alexandria.png", topic: "Cities", URL: ""},
{description: "Boston", objects: "", location: "United States", date: "42.4", actor: "4.4 million", category: "North America", image: "Boston.png", topic: "Cities", URL: ""},
{description: "Barcelona", objects: "", location: "Spain", date: "41.4", actor: "4.2 million", category: "Europe", image: "Barcelona.png", topic: "Cities", URL: ""},
{description: "Ankara", objects: "", location: "Turkey", date: "39.9", actor: "4.2 million", category: "Asia", image: "Ankara.png", topic: "Cities", URL: ""},
{description: "Rome", objects: "", location: "Italy", date: "41.9", actor: "3.8 million", category: "Europe", image: "Rome.png", topic: "Cities", URL: ""},
{description: "Sydney", objects: "", location: "Australia", date: "-33.9", actor: "3.8 million", category: "Australia", image: "Sydney.png", topic: "Cities", URL: ""},
{description: "Naples", objects: "", location: "Italy", date: "40.8", actor: "3.7 million", category: "Europe", image: "Naples.png", topic: "Cities", URL: ""},
{description: "Detroit", objects: "", location: "United States", date: "42.3", actor: "3.7 million", category: "North America", image: "Detroit.png", topic: "Cities", URL: ""},
{description: "Aberdeen", objects: "", location: "Scotland", date: "57.2", actor: "212 thousand", category: "Atlantic Islands", image: "Aberdeen.png", topic: "Cities", URL: ""},
{description: "Adelaide", objects: "", location: "Australia", date: "-34.9", actor: "1.2 million", category: "Australia", image: "Adelaide.png", topic: "Cities", URL: ""},
{description: "Algiers", objects: "", location: "Algeria", date: "36.8", actor: "1.6 million", category: "Africa", image: "Algiers.png", topic: "Cities", URL: ""},
{description: "Amsterdam", objects: "", location: "Netherlands", date: "52.22", actor: "780 thousand", category: "Europe", image: "Amsterdam.png", topic: "Cities", URL: ""},
{description: "Asuncion", objects: "", location: "Paraguay", date: "-25.3", actor: "513 thousand", category: "South America", image: "Asuncion.png", topic: "Cities", URL: ""},
{description: "Athens", objects: "", location: "Greece", date: "40", actor: "789 thousand", category: "Europe", image: "Athens.png", topic: "Cities", URL: ""},
{description: "Auckland", objects: "", location: "New Zealand", date: "-36.8", actor: "1.4 million", category: "Pacific Islands", image: "Auckland.png", topic: "Cities", URL: ""},
{description: "Belem", objects: "", location: "Brazil", date: "-1.5", actor: "2.1 million", category: "South America", image: "Belem.png", topic: "Cities", URL: ""},
{description: "Belfast", objects: "", location: "Northern Ireland", date: "54.6", actor: "281 thousand", category: "Atlantic Islands", image: "Belfast.png", topic: "Cities", URL: ""},
{description: "Belgrade", objects: "", location: "Serbia", date: "44.8", actor: "1.3 million", category: "Europe", image: "Belgrade.png", topic: "Cities", URL: ""},
{description: "Berlin", objects: "", location: "Germany", date: "52.5", actor: "3.5 million", category: "Europe", image: "Berlin.png", topic: "Cities", URL: ""},
{description: "Birmingham", objects: "", location: "England", date: "52.5", actor: "1.1 million", category: "Atlantic Islands", image: "Birmingham.png", topic: "Cities", URL: ""},
{description: "Bordeaux", objects: "", location: "France", date: "44.8", actor: "236 thousand", category: "Europe", image: "Bordeaux.png", topic: "Cities", URL: ""},
{description: "Bremen", objects: "", location: "Germany", date: "53.1", actor: "548 thousand", category: "Europe", image: "Bremen.png", topic: "Cities", URL: ""},
{description: "Brisbane", objects: "", location: "Australia", date: "-27.5", actor: "2.0 million", category: "Australia", image: "Brisbane.png", topic: "Cities", URL: ""},
{description: "Bristol", objects: "", location: "England", date: "51.5", actor: "428 thousand", category: "Atlantic Islands", image: "Bristol.png", topic: "Cities", URL: ""},
{description: "Brussels", objects: "", location: "Belgium", date: "50.9", actor: "1.1 million", category: "Europe", image: "Brussels.png", topic: "Cities", URL: ""},
{description: "Bucharest", objects: "", location: "Romania", date: "44.4", actor: "1.9 million", category: "Europe", image: "Bucharest.png", topic: "Cities", URL: ""},
{description: "Budapest", objects: "", location: "Hungary", date: "47.5", actor: "1.7 million", category: "Europe", image: "Budapest.png", topic: "Cities", URL: ""},
{description: "Cape Town", objects: "", location: "South Africa", date: "-33.9", actor: "3.7 million", category: "Africa", image: "CapeTown.png", topic: "Cities", URL: ""},
{description: "Caracas", objects: "", location: "Venezuela", date: "10.5", actor: "2.1 million", category: "South America", image: "Caracas.png", topic: "Cities", URL: ""},
{description: "Cayenne", objects: "", location: "French Guiana", date: "4.9", actor: "58 thousand", category: "South America", image: "Cayenne.png", topic: "Cities", URL: ""},
{description: "Chihuahua", objects: "", location: "Mexico", date: "28.6", actor: "809 thousand", category: "Central America", image: "Chihuahua.png", topic: "Cities", URL: ""},
{description: "Copenhagen", objects: "", location: "Denmark", date: "55.7", actor: "559 thousand", category: "Europe", image: "Copenhagen.png", topic: "Cities", URL: ""},
{description: "Dakar", objects: "", location: "Senegal", date: "14.7", actor: "1.1 million", category: "Africa", image: "Dakar.png", topic: "Cities", URL: ""},
{description: "Darwin", objects: "", location: "Australia", date: "-12.5", actor: "128 thousand", category: "Australia", image: "Darwin.png", topic: "Cities", URL: ""},
{description: "Djibouti", objects: "", location: "Djibouti", date: "11.8", actor: "860 thousand", category: "Africa", image: "Djibouti.png", topic: "Cities", URL: ""},
{description: "Dublin", objects: "", location: "Ireland", date: "53.3", actor: "528 thousand", category: "Atlantic Islands", image: "Dublin.png", topic: "Cities", URL: ""},
{description: "Edinburgh", objects: "", location: "Scotland", date: "56", actor: "495 thousand", category: "Europe", image: "Edinburgh.png", topic: "Cities", URL: ""},
{description: "Frankfurt", objects: "", location: "Germany", date: "50.1", actor: "692 thousand", category: "Europe", image: "Frankfurt.png", topic: "Cities", URL: ""},
{description: "Georgetown", objects: "", location: "Guyana", date: "6.8", actor: "134 thousand", category: "South America", image: "Georgetown.png", topic: "Cities", URL: ""},
{description: "Glasgow", objects: "", location: "Scotland", date: "55.9", actor: "599 thousand", category: "Europe", image: "Glasgow.png", topic: "Cities", URL: ""},
{description: "Guatemala City", objects: "", location: "Guatemala", date: "14.6", actor: "1.0 million", category: "Central America", image: "GuatemalaCity.png", topic: "Cities", URL: ""},
{description: "Guayaquil", objects: "", location: "Ecuador", date: "-2.2", actor: "2.3 million", category: "South America", image: "Guayaquil.png", topic: "Cities", URL: ""},
{description: "Hamburg", objects: "", location: "Germany", date: "55.6", actor: "1.8 million", category: "Europe", image: "Hamburg.png", topic: "Cities", URL: ""},
{description: "Hammerfest", objects: "", location: "Norway", date: "70.7", actor: "10.3 thousand", category: "Scandinavia", image: "Hammerfest.png", topic: "Cities", URL: ""},
{description: "Havana", objects: "", location: "Cuba", date: "23.1", actor: "2.1 million", category: "Atlantic Islands", image: "Havana.png", topic: "Cities", URL: ""},
{description: "Helsinki", objects: "", location: "Finland", date: "60.2", actor: "1.3 million", category: "Scandinavia", image: "Helsinki.png", topic: "Cities", URL: ""},
{description: "Hobart", objects: "", location: "Tasmania", date: "-42.9", actor: "215 thousand", category: "Australia", image: "Hobart.png", topic: "Cities", URL: ""},
{description: "Iquique", objects: "", location: "Chile", date: "-20.2", actor: "182 thousand", category: "South America", image: "Iquique.png", topic: "Cities", URL: ""},
{description: "Irkutsk", objects: "", location: "Russia", date: "52.3", actor: "588 thousand", category: "Asia", image: "Irkutsk.png", topic: "Cities", URL: ""},
{description: "Kingston", objects: "", location: "Jamaica", date: "18", actor: "579 thousand", category: "Atlantic Islands", image: "Kingston.png", topic: "Cities", URL: ""},
{description: "La Paz", objects: "", location: "Bolivia", date: "-16.5", actor: "790 thousand", category: "South America", image: "LaPaz.png", topic: "Cities", URL: ""},
{description: "Lisbon", objects: "", location: "Portugal", date: "38.7", actor: "475 thousand", category: "Europe", image: "Lisbon.png", topic: "Cities", URL: ""},
{description: "Liverpool", objects: "", location: "England", date: "53.4", actor: "466 thousand", category: "Atlantic Islands", image: "Liverpool.png", topic: "Cities", URL: ""},
{description: "Lyon", objects: "", location: "France", date: "45.8", actor: "475 thousand", category: "Europe", image: "Lyon.png", topic: "Cities", URL: ""},
{description: "Manchester", objects: "", location: "England", date: "53.5", actor: "2.6 million", category: "Atlantic Islands", image: "Manchester.png", topic: "Cities", URL: ""},
{description: "Marseille", objects: "", location: "France", date: "43.3", actor: "851 thousand", category: "Europe", image: "Marseille.png", topic: "Cities", URL: ""},
{description: "Mecca", objects: "", location: "Saudi Arabia", date: "21.4", actor: "2 million", category: "Middle East", image: "Mecca.png", topic: "Cities", URL: ""},
{description: "Melbourne", objects: "", location: "Australia", date: "-37.8", actor: "4.1 million", category: "Australia", image: "Melbourne.png", topic: "Cities", URL: ""},
{description: "Montevideo", objects: "", location: "Uruguay", date: "-34.9", actor: "1.3 million", category: "South America", image: "Montevideo.png", topic: "Cities", URL: ""},
{description: "Munich", objects: "", location: "Germany", date: "48.1", actor: "1.4 million", category: "Europe", image: "Munich.png", topic: "Cities", URL: ""},
{description: "Nagasaki", objects: "", location: "Japan", date: "32.8", actor: "444 thousand", category: "Pacific Islands", image: "Nagasaki.png", topic: "Cities", URL: ""},
{description: "Nairobi", objects: "", location: "Kenya", date: "-1.3", actor: "3.1 million", category: "Africa", image: "Nairobi.png", topic: "Cities", URL: ""},
{description: "Newcastle-on-Tyne", objects: "", location: "England", date: "55", actor: "1 million", category: "Atlantic Islands", image: "NewcastleonTyne.png", topic: "Cities", URL: ""},
{description: "Odessa", objects: "", location: "Ukraine", date: "46.5", actor: "991 thousand", category: "Asia", image: "Odessa.png", topic: "Cities", URL: ""},
{description: "Oslo", objects: "", location: "Norway", date: "60", actor: "593 thousand", category: "Scandinavia", image: "Oslo.png", topic: "Cities", URL: ""},
{description: "Panama City", objects: "", location: "Panama", date: "9", actor: "36 thousand", category: "Central America", image: "PanamaCity.png", topic: "Cities", URL: ""},
{description: "Paramaribo", objects: "", location: "Suriname", date: "5.9", actor: "250 thousand", category: "South America", image: "Paramaribo.png", topic: "Cities", URL: ""},
{description: "Perth", objects: "", location: "Australia", date: "-31.9", actor: "1.7 million", category: "Australia", image: "Perth.png", topic: "Cities", URL: ""},
{description: "Plymouth", objects: "", location: "England", date: "50.4", actor: "241 thousand", category: "Atlantic Islands", image: "Plymouth.png", topic: "Cities", URL: ""},
{description: "Prague", objects: "", location: "Czech Republic", date: "50.1", actor: "1.3 million", category: "Europe", image: "Prague.png", topic: "Cities", URL: ""},
{description: "Reykjavik", objects: "", location: "Iceland", date: "64.1", actor: "118 thousand", category: "Atlantic Islands", image: "Reykjavik.png", topic: "Cities", URL: ""},
{description: "Salvador", objects: "", location: "Brazil", date: "-13", actor: "2.7 million", category: "South America", image: "Salvador.png", topic: "Cities", URL: ""},
{description: "Sofia", objects: "", location: "Bulgaria", date: "42.7", actor: "1.2 million", category: "Europe", image: "Sofia.png", topic: "Cities", URL: ""},
{description: "Stockholm", objects: "", location: "Sweden", date: "59.3", actor: "789 thousand", category: "Scandinavia", image: "Stockholm.png", topic: "Cities", URL: ""},
{description: "Antananarivo", objects: "", location: "Madagascar", date: "-18.9", actor: "710 thousand", category: "Africa", image: "Antananarivo.png", topic: "Cities", URL: ""},
{description: "Tripoli", objects: "", location: "Libya", date: "32.9", actor: "2.2 million", category: "Africa", image: "Tripoli.png", topic: "Cities", URL: ""},
{description: "Venice", objects: "", location: "Italy", date: "45.4", actor: "271 thousand", category: "Europe", image: "Venice.png", topic: "Cities", URL: ""},
{description: "Veracruz", objects: "", location: "Mexico", date: "19.2", actor: "552 thousand", category: "Central America", image: "Veracruz.png", topic: "Cities", URL: ""},
{description: "Vienna", objects: "", location: "Austria", date: "48.2", actor: "1.7 million", category: "Europe", image: "Vienna.png", topic: "Cities", URL: ""},
{description: "Vladivostok", objects: "", location: "Russia", date: "43.1", actor: "592 thousand", category: "Asia", image: "Vladivostok.png", topic: "Cities", URL: ""},
{description: "Warsaw", objects: "", location: "Poland", date: "52.2", actor: "1.7 million", category: "Europe", image: "Warsaw.png", topic: "Cities", URL: ""},
{description: "Wellington", objects: "", location: "New Zealand", date: "-41.3", actor: "200 thousand", category: "Pacific Islands", image: "Wellington.png", topic: "Cities", URL: ""},
{description: "Zurich", objects: "", location: "Switzerland", date: "47.4", actor: "367 thousand", category: "Europe", image: "Zurich.png", topic: "Cities", URL: ""},
{description: "Oxford", objects: "", location: "England", date: "51.8", actor: "150 thousand", category: "Atlantic Islands", image: "Oxford.png", topic: "Cities", URL: ""},
]
EventNum = 149